# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/design_1_frame_average_buffer_0_0.xci
# IP: The module: 'design_1_frame_average_buffer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer/blk_mem_average_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_average_buffer || ORIG_REF_NAME==blk_mem_average_buffer}]

# IP: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer_single/blk_mem_average_buffer_single.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_average_buffer_single || ORIG_REF_NAME==blk_mem_average_buffer_single}]

# XDC: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer/blk_mem_average_buffer_ooc.xdc

# XDC: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer_single/blk_mem_average_buffer_single_ooc.xdc

# IP: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/design_1_frame_average_buffer_0_0.xci
# IP: The module: 'design_1_frame_average_buffer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer/blk_mem_average_buffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_average_buffer || ORIG_REF_NAME==blk_mem_average_buffer}]

# IP: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer_single/blk_mem_average_buffer_single.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_average_buffer_single || ORIG_REF_NAME==blk_mem_average_buffer_single}]

# XDC: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer/blk_mem_average_buffer_ooc.xdc

# XDC: c:/Users/lingujia/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_0/ip/blk_mem_average_buffer_single/blk_mem_average_buffer_single_ooc.xdc
