# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_1/design_1_frame_average_buffer_0_1.xci
# IP: The module: 'design_1_frame_average_buffer_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_1/ip/blk_mem_average_buffer/blk_mem_average_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_average_buffer || ORIG_REF_NAME==blk_mem_average_buffer}]

# XDC: c:/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_1/ip/blk_mem_average_buffer/blk_mem_average_buffer_ooc.xdc

# IP: C:/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_1/design_1_frame_average_buffer_0_1.xci
# IP: The module: 'design_1_frame_average_buffer_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_1/ip/blk_mem_average_buffer/blk_mem_average_buffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_average_buffer || ORIG_REF_NAME==blk_mem_average_buffer}]

# XDC: c:/ece532_project/ece532_project.srcs/sources_1/bd/design_1/ip/design_1_frame_average_buffer_0_1/ip/blk_mem_average_buffer/blk_mem_average_buffer_ooc.xdc
